### ISSUE TITLE
Add Vid Compose to F-Droid

### ISSUE THREAD

**Issue by Korb** [rajaumair7890/VidCompose#1]
Currently when I search for F-Droid using "vid compose" I get the message

> No matching applications available.

I suggest considering the possibility of installing and updating Better Player, including through this distribution platform, as it is free and decentralized, unlike Google Play.

**Comment by bitsbyumair** [comment]
It's not production ready and it was mere an experiment. If I get some free time, I can consider improving it and releasing to F-droid or even google play!
